# **LU Decomposition:**

---
**Definition:**

LU Decomposition is a numerical linear algebra technique used to factorize a square matrix A into the product of two triangular matrices:
         
###         A=LU

where:

**L** is a unit lower triangular matrix, containing the elimination
multipliers below its main diagonal.

**U** is an upper triangular matrix, obtained after performing Gaussian elimination on A.

**Example:**

For a 3×3 matrix:

```
A = [ a11  a12  a13
      a21  a22  a23
      a31  a32  a33 ]
```

The LU decomposition has the form:


```
L = [ 1    0    0

      L21  1    0

      l31  l32  1 ]

U = [ u11  u12  u13

      0    u22  u23

      0    0    u33 ]
```
Therefore:

A = LU

```
  A = [[ 1     0     0]        *  [[ u11  u12  u13]

      [L21    1   0  ]      *   [0     u22   u23]

     [ L31    L32    1   ] ] *    [0    0      u33]]
```



**Algorithm for Performing Doolittle LU Decomposition :**


Given:
    A x = b

we decompose into:

    A = LU
    LU x = b
Let:

    Ly = b

    using forward substitution, find the values of y and then;

    Solve:

        Ux = y

    The values obtained for x are the final solution.


    Verify the result by checking:

             Ax = b
  
 ### **Why Do We Need Computer Coding for LU Decomposition?**

Although LU Decomposition can be done manually for small matrices, manual calculations for large matrices can be tedious and error prone. By computer coding the processes of decomposition, forward substitution and back substitution, we can solve large systems of equations rapidly, accurately and efficiently. It also allows to reuse the method for different input matrices.

### **Advantages of LU decomposition:**

1. LU Decomposition is a useful technique to solve several systems of equations with the same coefficient matrix and different constant vectors.

 2. It is also used in numerical methods for matrix inversion and determinant calculation. It has the same computational complexity as Gaussian elimination, but is more efficient when solving multiple systems of equations.

 3. Gaussian Elimination transforms A into U, while LU Decomposition also records the elimination factors in L.This makes LU Decomposition particularly useful and provide more accuracy then Guassian Elimination method.

 4. LU Decomposition uses the same elimination process, but instead of discarding the elimination multipliers, it stores them in L. Then the resulting L and U matrices can be reused to solve systems efficiently.



### **Algorithm for coding:**

Algorithm: LU Decomposition

Input:
    A = coefficient matrix
    b = RHS vector

Output:
    x = solution vector

Step 1:
    Set n = number of rows of A.

Step 2:
    Initialize L as an identity matrix of size n × n.

Step 3:
    Set U = A.

Step 4:
    For i = 0 to n - 2:

        For j = i + 1 to n - 1:

            Calculate the elimination factor:

                factor = U[j][i] / U[i][i]

            Store the factor in L:

                L[j][i] = factor

            Perform row replacement:

                U[j] = U[j] - factor × U[i]

Step 5:
    Solve the lower triangular system:

        L y = b

    using forward substitution.

Step 6:
    Solve the upper triangular system:

        U x = y

    using back substitution.

Step 7:
    Return L, U, and x.

Step 8:
    Verify the decomposition:

        A = L × U

    and verify the solution:

        A × x ≈ b

###**Question no 01:**

Write a Python program using NumPy to perform LU decomposition of a given square matrix (A) into lower triangular matrix (L) and upper triangular matrix (U) such that (A=LU). The program should calculate the decomposition using Gaussian elimination, display the matrices (L) and (U), verify the decomposition by computing (L@U) and comparing it with the original matrix (A), and calculate the decomposition error using the matrix norm (|A-LU|).

In [ ]:
import numpy as np
def LU_decomposition(A):
  A=A.astype(float)
  n=len(A)
  L=np.eye(n)
  U=A.copy()
  for i in range(n-1):
    for j in range(i+1,n):
      factor=U[j,i]/U[i,i]
      L[j,i]=factor
      U[j]=U[j]-factor*U[i]
  return L,U
A= np.array([[1,2,3],[4,6,7],[0,1,3]], dtype=float)
L,U=LU_decomposition(A)
print("\nL=",L)
print("\nU=",U)
print("\nVerification: L @ U")
print(L @ U)
print("\nthe matrix A is:   " )
print(A)
error = np.linalg.norm(A - L @ U)

print("\nDecomposition Error:", error)



L= [[ 1.   0.   0. ]
 [ 4.   1.   0. ]
 [ 0.  -0.5  1. ]]

U= [[ 1.   2.   3. ]
 [ 0.  -2.  -5. ]
 [ 0.   0.   0.5]]

Verification: L @ U
[[1. 2. 3.]
 [4. 6. 7.]
 [0. 1. 3.]]

the matrix A is:   
[[1. 2. 3.]
 [4. 6. 7.]
 [0. 1. 3.]]

Decomposition Error: 0.0


### **Question no 02:**

Write a Python program using NumPy to solve a system of linear equations (Ax=b) using LU decomposition. The program should decompose the coefficient matrix (A) into a unit lower triangular matrix (L) and an upper triangular matrix (U) such that (A=LU), solve the lower triangular system (Ly=b) using forward substitution, solve the upper triangular system (Ux=y) using back substitution, display (L), (U), (y), and the final solution (x), verify the solution by comparing (A@x) with (b), calculate the residual error using the matrix norm, and verify the LU decomposition by comparing (L@U) with the original matrix (A).


In [ ]:
import numpy as np
def LU_decomposition(A):
  A=A.astype(float)
  n=len(A)
  L=np.eye(n)
  U=A.copy()
# LU decompostion Simulation
  for i in range(n-1):
    for j in range(i+1,n):
      factor = U[j,i]/U[i,i]
      L[j,i]= factor
      U[j]=U[j]-factor*U[i]
  return L,U
def forward_substitution(L,b):
  n=len(b)
  y=np.zeros(n)
  for i in range(n):
    sum_values=0
    for j in range(i):
      sum_values+=L[i,j]*y[j]
    y[i]=(b[i]- sum_values)/L[i,i]
  return y
def back_substitution(U, y):

    n = len(y)

    x = np.zeros(n)

    for i in range(n - 1, -1, -1):

        sum_values = 0

        for j in range(i + 1, n):

            sum_values += U[i, j] * x[j]

        x[i] = (y[i] - sum_values) / U[i, i]

    return x
A = np.array([
    [2, 1, 1],
    [4, 4, 3],
    [1, 2, 2]], dtype=float)

b = np.array([5, 13, 7], dtype=float)

L, U = LU_decomposition(A)

y = forward_substitution(L, b)

x = back_substitution(U, y)

print("L =")
print(L)

print("\nU =")
print(U)

print("\ny =", y)

print("\nSolution:")
print("x = ", x)
print("\nverification::")
print("A @ x =", A @ x)
print("b  =", b)

residual = np.linalg.norm(A @ x - b)

print("\nResidual = ", residual)

# VERIFICATION OF A = LU:

print("\nVerification of A = LU:")

print("L @ U =")
print(L @ U)

print("\nOriginal A =")
print(A)
# Decomposition Error:
decomposition_error = np.linalg.norm(A - L @ U)

print("\nDecomposition Error:", decomposition_error)


L =
[[1.   0.   0.  ]
 [2.   1.   0.  ]
 [0.5  0.75 1.  ]]

U =
[[2.   1.   1.  ]
 [0.   2.   1.  ]
 [0.   0.   0.75]]

y = [5.   3.   2.25]

Solution:
x =  [1. 0. 3.]

verification::
A @ x = [ 5. 13.  7.]
b  = [ 5. 13.  7.]

Residual =  0.0

Verification of A = LU:
L @ U =
[[2. 1. 1.]
 [4. 4. 3.]
 [1. 2. 2.]]

Original A =
[[2. 1. 1.]
 [4. 4. 3.]
 [1. 2. 2.]]

Decomposition Error: 0.0


###**LU Decomposition with Partial Pivoting:**

"If the current pivot is zero (or very small), we select a suitable larger pivot from the rows below and swap the rows to ensure numerical stability."
  
   A= LU
   
   PA= LU

where, P is the permutation matrix, that records the row swap.

**pivot_row = np.argmax(np.abs(U[i:n, i])) + i**

i = 0

```
U = [ 0  2  1
      2  4  1
      1  1  2 ]

U[0:n, 0]

[0
 2
 1]

np.argmax([0, 2, 1])

1 largest value=2 it index is 1

pivot_row = 1 + i
pivot_row = 1

Python index     Mathematical row

0                Row 1
1                Row 2
2                Row 3
The + i converts the local index returned by argmax() back into the actual matrix row index.
```
**if U[pivot_row, i] == 0:**

[0
 0
 0]

there is no non-zero pivot coloumn, that's why we can't perform partial pivoting.

**if pivot_row != i:**
i = 0
pivot_row = 1
then,
Row 1 ↔ Row 2

If the best pivot isn't already in the current row, swap rows.

**P[[i, pivot_row]] = P[[pivot_row, i]]**

also the permutation matrix swap.

**if i > 0:  L[[i, pivot_row], :i] = L[[pivot_row, i], :i]**

If we have already calculated some multipliers in L...
Swap only the previously calculated multipliers in L.



###**Question no 03:**

Write a Python program using NumPy to perform LU decomposition with partial pivoting for a given square matrix (A). The program should select the largest absolute pivot element from the current column, swap rows when necessary, and construct a permutation matrix (P), a unit lower triangular matrix (L), and an upper triangular matrix (U) such that (PA=LU). The program should display (P), (L), and (U), verify the decomposition by comparing (P@A) with (L@U), and calculate the decomposition error using the matrix norm (|PA-LU|).


In [ ]:
import numpy as np
def LU_decomposition(A):
    A = A.astype(float)
    n = len(A)
    L = np.eye(n)
    U = A.copy()
    P = np.eye(n)
    for i in range(n - 1):
        pivot_row = np.argmax(np.abs(U[i:n, i])) + i
        print("\nCurrent column:", i)
        print("Pivot row:", pivot_row)
        if U[pivot_row, i] == 0:
            raise ValueError("Singular matrix: no unique solution exists.")
        if pivot_row != i:
            U[[i, pivot_row]] = U[[pivot_row, i]]
            P[[i, pivot_row]] = P[[pivot_row, i]]
            if i > 0:
                L[[i, pivot_row], :i] = L[[pivot_row, i], :i]

            print("Rows swapped.")
        for j in range(i + 1, n):

            factor = U[j, i] / U[i, i]

            L[j, i] = factor

            U[j] = U[j] - factor * U[i]

    return P, L, U
A = np.array([
    [0, 1, 1],
    [4, 4, 3],
    [1, 2, 2]
], dtype=float)
P, L, U = LU_decomposition(A)
print("\nP =")
print(P)
print("\nL =")
print(L)
print("\nU =")
print(U)
print("\nPA =")
print(P @ A)
print("\nLU =")
print(L @ U)
error = np.linalg.norm(P @ A - L @ U)

print("\nDecomposition Error:", error)


Current column: 0
Pivot row: 1
Rows swapped.

Current column: 1
Pivot row: 1

P =
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]

L =
[[1.   0.   0.  ]
 [0.   1.   0.  ]
 [0.25 1.   1.  ]]

U =
[[4.   4.   3.  ]
 [0.   1.   1.  ]
 [0.   0.   0.25]]

PA =
[[4. 4. 3.]
 [0. 1. 1.]
 [1. 2. 2.]]

LU =
[[4. 4. 3.]
 [0. 1. 1.]
 [1. 2. 2.]]

Decomposition Error: 0.0


**Steps to Follow for Solving LU decomposition with partial pivoting:**
1. Ax=b
2. PAx=Pb
3. LUx=Pb
4. Ux=y  # Backword Substitution
5. Ly=Pb # Forward Substitution

solving for y, then find the y's and go to step 4, for solving x.

###**Question no 04:**

Write a Python program using NumPy to solve a system of linear equations (Ax=b) using LU decomposition with partial pivoting. The program should decompose the coefficient matrix (A) into a permutation matrix (P), a unit lower triangular matrix (L), and an upper triangular matrix (U) such that (PA=LU). It should apply the same row permutations to the right-hand-side vector by computing (Pb), solve (Ly=Pb) using forward substitution, solve (Ux=y) using backward substitution, display the solution vector (x), verify the solution by comparing (Ax) with (b), and calculate the residual error using the matrix norm (|Ax-b|).


In [ ]:
import numpy as np
def LU_decomposition(A):
  A=A.astype(float)
  n=len(A)
  L=np.eye(n)
  U=A.copy()
  P=np.eye(n)
  for i in range(n-1):
    pivot_row = np.argmax(np.abs(U[i:n, i])) + i
    print("\nCurrent column:", i)
    print("Pivot row:", pivot_row)
    if U[pivot_row,i]==0:
      raise ValueError("Singular Matrix not unique solution")
    if pivot_row!=i:
      U[[i,pivot_row]]=U[[pivot_row,i]]
      P[[i,pivot_row]]=P[[pivot_row,i]]
      if i>0:
        L[[i,pivot_row],:i]= L[[pivot_row, i], :i]
        print("Rows swapped.")
    for j in range(i+1,n):
      factor=U[j,i]/U[i,i]
      L[j,i]=factor
      U[j]=U[j]-factor*U[i]
    return P,L,U

def forward_substitution(L, b): # Ly=Pb
    n = len(b)
    y = np.zeros(n)
    for i in range(n):
        y[i] = b[i] - np.dot(L[i, :i], y[:i])
    return y
def backward_substitution(U, y):
    n = len(y)
    x = np.zeros(n)

    for i in range(n - 1, -1, -1):
        if U[i, i] == 0:
            raise ValueError("Singular matrix: no unique solution exists.")
        x[i] = (y[i] - np.dot(U[i, i + 1:], x[i + 1:])) / U[i, i]
    return x
A = np.array([
    [0, 1, 1],
    [4, 4, 3],
    [1, 2, 2]], dtype=float)
b = np.array([2, 11, 7], dtype=float)
P, L, U = LU_decomposition(A)
Pb = P @ b

print("\nPb =")
#  Solve Ly = Pb
y = forward_substitution(L, Pb)
print("\ny =")
print(y)
# Solve Ux = y
x = backward_substitution(U, y)
print("\nx =")
print(x)
# Verification of the solution
print("\nAx =")
print(A @ x)
print("\nb =")
print(b)
error = np.linalg.norm(A @ x - b)

print("\nResidual Error:", error)



Current column: 0
Pivot row: 1

Pb =

y =
[11.    2.    4.25]

x =
[ 1.6 -1.4  3.4]

Ax =
[ 2.  11.   5.6]

b =
[ 2. 11.  7.]

Residual Error: 1.4000000000000004


##**Question no 05:**

Write a Python program using NumPy to solve multiple systems of linear equations with the same coefficient matrix (A) using LU decomposition with partial pivoting. The program should factorize (A) into a permutation matrix (P), a unit lower triangular matrix (L), and an upper triangular matrix (U) such that (PA=LU), and then reuse the same LU factors to efficiently solve (Ax=b1) and (Ax=b2) for two different right-hand-side vectors. The program should apply the permutation to each right-hand side, solve the resulting triangular systems using forward and backward substitution, display the solutions (x1) and (x2), verify each solution by computing (A@x), and calculate the residual error (|Ax-b|) for both systems.


In [ ]:
import numpy as np
def LU_decomposition(A):
    A = A.astype(float)
    n = len(A)
    L = np.eye(n)
    U = A.copy()
    P = np.eye(n)
    for i in range(n - 1):
        pivot_row = np.argmax(np.abs(U[i:n, i])) + i
        if abs(U[pivot_row, i]) < 1e-12:
            raise ValueError("Singular or nearly singular matrix.")
        if pivot_row != i:
            U[[i, pivot_row]] = U[[pivot_row, i]]
            P[[i, pivot_row]] = P[[pivot_row, i]]
            if i > 0:
                L[[i, pivot_row], :i] = L[[pivot_row, i], :i]
        for j in range(i + 1, n):

            factor = U[j, i] / U[i, i]

            L[j, i] = factor

            U[j] = U[j] - factor * U[i]
    return P, L, U
def forward_substitution(L, b):
    n = len(b)
    y = np.zeros(n)
    for i in range(n):
        y[i] = b[i] - np.dot(L[i, :i], y[:i])
    return y
def backward_substitution(U, y):
    n = len(y)
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = (y[i] - np.dot(U[i, i + 1:], x[i + 1:])) / U[i, i]
    return x
def solve_LU(P, L, U, b):
    Pb = P @ b
    #  Ly = Pb
    y = forward_substitution(L, Pb)

    #  Ux = y
    x = backward_substitution(U, y)
    return x
A = np.array([
    [0, 1, 1],
    [4, 4, 3],
    [1, 2, 2]
], dtype=float)
P, L, U = LU_decomposition(A)
print("P =")
print(P)
print("\nL =")
print(L)
print("\nU =")
print(U)
#  Ax = b1

b1 = np.array([2, 11, 7], dtype=float)

x1 = solve_LU(P, L, U, b1)
print("Solving Ax = b1")
print("\nb1 =")
print(b1)
print("\nx1 =")
print(x1)
print("\nA @ x1 =")
print(A @ x1)

error1 = np.linalg.norm(A @ x1 - b1)
print("\nResidual Error for b1:", error1)

# Ax = b2

b2 = np.array([5, 14, 8], dtype=float)

x2 = solve_LU(P, L, U, b2)
print("Solving Ax = b2")
print("\nb2 =")
print(b2)
print("\nx2 =")
print(x2)
print("\nA @ x2 =")
print(A @ x2)

error2 = np.linalg.norm(A @ x2 - b2)

print("\nResidual Error for b2:", error2)

P =
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]

L =
[[1.   0.   0.  ]
 [0.   1.   0.  ]
 [0.25 1.   1.  ]]

U =
[[4.   4.   3.  ]
 [0.   1.   1.  ]
 [0.   0.   0.25]]
Solving Ax = b1

b1 =
[ 2. 11.  7.]

x1 =
[ 3. -7.  9.]

A @ x1 =
[ 2. 11.  7.]

Residual Error for b1: 0.0
Solving Ax = b2

b2 =
[ 5. 14.  8.]

x2 =
[-2.  7. -2.]

A @ x2 =
[ 5. 14.  8.]

Residual Error for b2: 0.0


###  **Singular Matrix in LU decomposition:**         

```
            Matrix A
                 ↓
        Partial Pivoting
                 ↓
             PA = LU
                 ↓
       Check the pivots
          ↙           ↘
     Non-zero          Zero
        ↓                ↓
 Continue LU       Singular Matrix
        ↓                ↓
 Solve Ax=b       Cannot get unique
                  solution
```
Partial pivoting helps us choose a good non-zero pivot while singular-matrix detection tells us what to do if no suitable non-zero pivot exists.




###**Question no 06:**

Write a Python program using NumPy to perform LU decomposition with partial pivoting and detect whether a given matrix is singular or nearly singular. The program should use a tolerance threshold to identify zero or very small pivot elements, raise an appropriate error when the matrix is singular or nearly singular, and use exception handling to display the error message without stopping the program unexpectedly. Test the implementation using a singular matrix and display the matrix and the resulting error message.


In [ ]:
import numpy as np

def LU_decomposition(A):
    A = A.astype(float)
    n = len(A)
    L = np.eye(n)
    U = A.copy()
    P = np.eye(n)
    for i in range(n - 1):
        pivot_row = np.argmax(np.abs(U[i:n, i])) + i
        print("\nCurrent column:", i)
        print("Pivot row:", pivot_row)
        if abs(U[pivot_row, i]) < 1e-12:
            raise ValueError("Singular or nearly singular matrix.")
        if pivot_row != i:
            U[[i, pivot_row]] = U[[pivot_row, i]]
            P[[i, pivot_row]] = P[[pivot_row, i]]
            if i > 0:
                L[[i, pivot_row], :i] = L[[pivot_row, i], :i]
            print("Rows swapped.")
        for j in range(i + 1, n):
            factor = U[j, i] / U[i, i]
            L[j, i] = factor
            U[j] = U[j] - factor * U[i]
    if abs(U[n - 1, n - 1]) < 1e-12:
        raise ValueError("Singular or nearly singular matrix.")

    return P, L, U
A_singular = np.array([
    [1, 2],
    [2, 4]], dtype=float)
print("Testing Singular Matrix:")
print("\nA =")
print(A_singular)
try:
    P, L, U = LU_decomposition(A_singular)
    print("\nP =")
    print(P)
    print("\nL =")
    print(L)
    print("\nU =")
    print(U)
except ValueError as error:
    print("\nError:", error)

Testing Singular Matrix:

A =
[[1. 2.]
 [2. 4.]]

Current column: 0
Pivot row: 1
Rows swapped.

Error: Singular or nearly singular matrix.


##**Comparison with Numpy:**

###**Question no 07:**

Implement LU decomposition with partial pivoting to solve (Ax=b), then compare the solution obtained from the custom LU method with NumPy’s `np.linalg.solve()`. Calculate the difference between the two solutions and compare their residual errors to verify the accuracy of the custom implementation.


In [ ]:
import numpy as np
def LU_decomposition(A):
    A = A.astype(float)
    n = len(A)
    L = np.eye(n)
    U = A.copy()
    P = np.eye(n)

    for i in range(n - 1):
        pivot_row = np.argmax(np.abs(U[i:n, i])) + i
        if abs(U[pivot_row, i]) < 1e-12:
            raise ValueError("Singular or nearly singular matrix.")
        if pivot_row != i:
            U[[i, pivot_row]] = U[[pivot_row, i]]
            P[[i, pivot_row]] = P[[pivot_row, i]]
            if i > 0:
                L[[i, pivot_row], :i] = L[[pivot_row, i], :i]
        for j in range(i + 1, n):

            factor = U[j, i] / U[i, i]

            L[j, i] = factor

            U[j] = U[j] - factor * U[i]
    if abs(U[n - 1, n - 1]) < 1e-12:
        raise ValueError("Singular or nearly singular matrix.")
    return P, L, U
def forward_substitution(L, b):
    n = len(b)
    y = np.zeros(n)

    for i in range(n):
        y[i] = b[i] - np.dot(L[i, :i], y[:i])
    return y
def backward_substitution(U, y):
    n = len(y)
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = (y[i] - np.dot(U[i, i + 1:], x[i + 1:])) / U[i, i]
    return x
def solve_LU(P, L, U, b): # Solve Ax=b using LU method
    Pb = P @ b # Ly = Pb
    y = forward_substitution(L, Pb) # Ux = y
    x = backward_substitution(U, y)
    return x
A = np.array([
    [0, 1, 1],
    [4, 4, 3],
    [1, 2, 2]
], dtype=float)

b = np.array([2, 11, 7], dtype=float)

# Our LU Method
P, L, U = LU_decomposition(A)
x_LU = solve_LU(P, L, U, b)
# NumPy Method
x_numpy = np.linalg.solve(A, b)
# Display our Results:
print("Solution using our LU method:")
print(x_LU)
print("\nSolution using NumPy:")
print(x_numpy)
# Compare the solutions
comparison_error = np.linalg.norm(x_LU - x_numpy)
print("\nDifference between LU and NumPy:")
print(comparison_error)
print("\n Verification:")
residual_LU = np.linalg.norm(A @ x_LU - b)
residual_numpy = np.linalg.norm(A @ x_numpy - b)
print("\nResidual error using our LU method:")
print(residual_LU)
print("\nResidual error using NumPy:")
print(residual_numpy)

Solution using our LU method:
[ 3. -7.  9.]

Solution using NumPy:
[ 3. -7.  9.]

Difference between LU and NumPy:
0.0

 Verification:

Residual error using our LU method:
0.0

Residual error using NumPy:
0.0


### **Validation against NumPy**

The implemented LU decomposition with partial pivoting was validated against NumPy's . The computed solution agrees with NumPy to numerical precision, confirming the correctness of the implementation.np.linalg.solve()

# **Conclusion**

This project successfully implemented LU decomposition with partial pivoting for solving linear systems of equations. The method performs row pivoting to select suitable pivots and computes the decomposition (PA=LU). The resulting (L) and (U) matrices were then used to solve (Ax=b) through forward and backward substitution.

The implementation was tested for singular matrices and verified using the residual error. Finally, the computed solutions were compared with NumPy's `np.linalg.solve()` and showed agreement to numerical precision, confirming the correctness and reliability of the implementation.
