
# **Gaussian Elimination Method:**

##**Definition:**

  **System of linear equations**

A system of linear equations means we have two or more equations containing unknown variables, and we want to find the values of those variables that satisfy all equations simultaneously.

**Example:**

 2x+y−z=8

−3x−y+2z=-11

−2x+y+2z=-3

We have 3 equations and 3 unknowns:

x,y,z

**Our objective is to find x,y,z.**

## **Steps to Follow:**


**Augmented Matrix**

Instead of writing the equations again and again in each step, we can represent them as a matrix form.

It can be written as:

```  
  2   1  -1 |   8
 -3  -1   2 | -11
 -2   1   2 |  -3

```
This is called Augumented Matrix.

 **Elementary Row Operations:**

Gaussian Elimination works by changing rows.

There are three basic row operations.

1. Operation 1 — Swap  any two rows in augumented matrix.

2. Operation 2 — Multiply a row by non-zero scalor.

3. Operation 3 — We can add and subtract  a multiple of one row from another row.

**Forward Elimination:**


```
[ *  *  * | * ]
[ 0  *  * | * ]
[ 0  0  * | * ]
```
 This is called an upper triangular matrix.

**Back Substitution:**

Now we work from the bottom equation upward,to find the unknown variable.

## **Applications:**

Gaussian elimination is a powerful numerical method for solving systems of linear equations, which is a fundamental problem in various fields.
such as;

**Machine Learning:**

Supports linear algebra operations used in data analysis and learning algorithms.

**Physics and Engineering:**

Used to solve problems like the motion of masses connected by springs or electrical circuits described by Kirchhoff's laws.


**Computer Graphics:** Employed in 3D transformations, image rendering, and lighting calculations.


**Cryptography:** Helps solve equations used in coding, encryption, and error correction.


---

## **How Forward Elimination Works?**

Forward elimination transforms the augmented matrix into an upper triangular matrix by eliminating the entries below each pivot element.

For a linear system

$$
Ax=b
$$

the augmented matrix is written as:

$$
\left[
\begin{array}{ccc|c}
1 & 1 & 1 & 6\\
2 & 3 & 1 & 10\\
1 & 2 & 3 & 13
\end{array}
\right]
$$

In Python, the matrix is stored using zero-based indexing:

$$
A[\text{row}][\text{column}]
$$

For example:

- `A[0][0]` → row 0, column 0 → first pivot
- `A[1][1]` → row 1, column 1 → second pivot
- `A[2][2]` → row 2, column 2 → third pivot

### **First Pivot**

The first pivot is:

$$
A[0][0]=1
$$

The element below the pivot that we want to eliminate is:
$$
A[1][0]=2
$$

The elimination factor is calculated as:

$$
\text{factor}=\frac{A[1][0]}{A[0][0]}
$$
Therefore,

$$
\text{factor}=\frac{2}{1}=2
$$

The target row is updated using:

$$
A[j]=A[j]-\text{factor}\times A[i]
$$

For row 1:

$$
R_1=R_1-2R_0
$$

giving

$$
[2,\;3,\;1\mid10]
-
2[1,\;1,\;1\mid6]
=
[0,\;1,\;-1\mid-2]
$$

The matrix therefore becomes:

$$
\left[
\begin{array}{ccc|c}
1 & 1 & 1 & 6\\
0 & 1 & -1 & -2\\
1 & 2 & 3 & 13
\end{array}
\right]
$$

The same process is then applied to the remaining rows and subsequent pivots until an upper triangular matrix is obtained.

### Python Logic

The essential operation is:

```python
factor = A[j][i] / A[i][i]
A[j] = A[j] - factor * A[i]

## **Back Substitution**

After forward elimination, the augmented matrix is transformed into an upper triangular system:

\begin{aligned}
a_{00}x+a_{01}y+a_{02}z &= b_0\\
a_{11}y+a_{12}z &= b_1\\
a_{22}z &= b_2
\end{aligned}


Back substitution solves the unknowns starting from the last row and moving upward.

### **Python Logic**

```python
for i in range(n - 1, -1, -1):
    sum_value = 0

    for j in range(i + 1, n):
        sum_value += A[i][j] * x[j]

    x[i] = (A[i][n] - sum_value) / A[i][i]

# **Question no 01:**

A company uses three types of machines to produce three products. The production requirements are represented by the following system of linear equations:

$$x_1 + x_2 + x_3 = 6$$

$$2x_1 + 3x_2 + x_3 = 10$$

$$x_1 + 2x_2 + 3x_3 = 13$$

 this,represents the production quantities of the three products.Use the Gaussian Elimination method to determine the values of x1 ,x2 ,x3. Then interpret what each value means in the context of the production problem.

In [ ]:
import numpy as np
A = np.array([
    [1, 1, 1, 6],
    [2, 3, 1, 10],
    [1, 2, 3, 13]
], dtype=float)
n = len(A)
print("MATRIX A")
print(A)

# Forward Elimination
for i in range(n-1): # to call pivot value
# A pivot is the element that we use to eliminate the entries below.
  for j in range(i+1,n):# j identifies the rows below the pivot that we want to change.
    scalor= A[j][i]/A[i][i]#It tells to the python, what factor we used to make zero.
    A[j]=A[j]-scalor*A[i]# Subtract that multiple of the pivot row from the current row so that the selected value becomes zero.
print("\nUpper Triangular Matrix:")
print(A)

# Back Substitution
x= np.zeros(n)
for i in range(n-1,-1,-1): #Start from the last equation and move upward to find the unknowns.
  sum_values=0 # Start counting the known terms from zero.
  for j in range(i+1,n):
    sum_values +=A[i][j]*x[j] #Add each known term to the total.
  x[i] = (A[i][n] - sum_values) / A[i][i]

# Final Solution


print("\nSolution:")

for i in range(n):
    print("x" + str(i + 1), "=", x[i])





MATRIX A
[[ 1.  1.  1.  6.]
 [ 2.  3.  1. 10.]
 [ 1.  2.  3. 13.]]

Upper Triangular Matrix:
[[ 1.  1.  1.  6.]
 [ 0.  1. -1. -2.]
 [ 0.  0.  3.  9.]]

Solution:
x1 = 2.0
x2 = 1.0
x3 = 3.0


**Answer:**

Using Gaussian Elimination, the values of the unknowns are:

x1 = 1

x2 = 2

x3 = 3

Therefore, the company should produce 1 unit of the first product, 2 units of the second product, and 3 units of the third product.

# **Question no 02**:

A laboratory needs to determine the quantities of three chemical solutions x1, x2, x3 required for an experiment. The relationships between the quantities are:

$$2x_2 + x_3 = 5$$

$$2x_1 + 4x_2 + x_3 = 9$$

$$x_1 + x_2 + 2x_3 = 6$$

Use Gaussian Elimination with row swapping (pivoting) to determine x1,x2 , x3. Explain how the solution can be interpreted as the required quantities of the three chemical solutions

In [ ]:
import numpy as np

A = np.array([
    [0, 2, 1, 5],
    [2, 4, 1, 9],
    [1, 1, 2, 6]
], dtype=float)

n = len(A)
print(A)

# FORWARD ELIMINATION

for i in range(n - 1):

    print("Pivot Position:", i)
    print("Current Pivot =", A[i][i])

    # ROW SWAP / PIVOTIN

    if A[i][i] == 0:

        for k in range(i + 1, n):

            if A[k][i] != 0:
                A[[i, k]] = A[[k, i]]

                print("\nMatrix after Row Swap:")
                print(A)

                break

    # ROW SCALING


    if A[i][i] != 1:

        pivot = A[i][i]


        A[i] = A[i] / pivot

        print("\nMatrix after Row Scaling:")
        print(A)


    # ROW REPLACEMENT

    for j in range(i + 1, n):

        factor = A[j][i] / A[i][i]
        print("Factor =", factor)

        A[j] = A[j] - factor * A[i]

        print("\nMatrix after Row Replacement:")
        print(A)

print("\nUpper Triangular Matrix")

print(A)

# BACK SUBSTITUTION

x = np.zeros(n)

for i in range(n - 1, -1, -1):

    print("\nFinding x", i + 1)

    sum_value = 0

    # Add known terms
    for j in range(i + 1, n):

        sum_value += A[i][j] * x[j]

        print(
            "Coefficient:",
            A[i][j],
            "* Known value:",
            x[j],
            "=",
            sum_value)

    # Calculate unknown
    x[i] = ( A[i][n] - sum_value) / A[i][i]

    print(
        "x", i + 1,
        "=",
        x[i]
    )


print("Final Solution")


for i in range(n):

    print("x" + str(i + 1), "=", x[i]   )

[[0. 2. 1. 5.]
 [2. 4. 1. 9.]
 [1. 1. 2. 6.]]
Pivot Position: 0
Current Pivot = 0.0

Matrix after Row Swap:
[[2. 4. 1. 9.]
 [0. 2. 1. 5.]
 [1. 1. 2. 6.]]

Matrix after Row Scaling:
[[1.  2.  0.5 4.5]
 [0.  2.  1.  5. ]
 [1.  1.  2.  6. ]]
Factor = 0.0

Matrix after Row Replacement:
[[1.  2.  0.5 4.5]
 [0.  2.  1.  5. ]
 [1.  1.  2.  6. ]]
Factor = 1.0

Matrix after Row Replacement:
[[ 1.   2.   0.5  4.5]
 [ 0.   2.   1.   5. ]
 [ 0.  -1.   1.5  1.5]]
Pivot Position: 1
Current Pivot = 2.0

Matrix after Row Scaling:
[[ 1.   2.   0.5  4.5]
 [ 0.   1.   0.5  2.5]
 [ 0.  -1.   1.5  1.5]]
Factor = -1.0

Matrix after Row Replacement:
[[1.  2.  0.5 4.5]
 [0.  1.  0.5 2.5]
 [0.  0.  2.  4. ]]

Upper Triangular Matrix
[[1.  2.  0.5 4.5]
 [0.  1.  0.5 2.5]
 [0.  0.  2.  4. ]]

Finding x 3
x 3 = 2.0

Finding x 2
Coefficient: 0.5 * Known value: 2.0 = 1.0
x 2 = 1.5

Finding x 1
Coefficient: 2.0 * Known value: 1.5 = 3.0
Coefficient: 0.5 * Known value: 2.0 = 4.0
x 1 = 0.5
Final Solution
x1 = 0.5
x2 = 

**Answer:**

Using Gaussian Elimination with pivoting, the required quantities are:

x1 = 1

x2 = 2

x3 = 1

Therefore, the laboratory requires 1 unit of the first chemical solution, 2 units of the second chemical solution, and 1 unit of the third chemical solution.

# **Question no 03:**

An electrical engineer is analyzing a circuit containing three unknown currents x1, x2, x3 .Using Kirchhoff’s laws, the following system of equations is obtained:

$$2x_2 + x_3 = 5$$

$$2x_1 + 4x_2 + x_3 = 9$$

$$x_1 + x_2 + 2x_3 = 6$$

Use Gaussian Elimination with pivoting to determine the three unknown currents?

In [ ]:
A = np.array([
    [2, 1, 1],
    [4, -6, -2],
    [-2, 7, 2]
], dtype=float)

b = np.array([5, -2, 9], dtype=float)
n=len(b)
Ab= np.column_stack((A,b)) # It can create the augumented matrix
# Forward Elimination
for i in range(n-1):# It call the pivot values.
  for j in range(i+1,n):
    scalor= Ab[j][i]/Ab[i][i]
    Ab[j]=Ab[j]-scalor*Ab[i]
# Back Substitution
x= np.zeros(n)
for i in range(n - 1, -1, -1):

    x[i] = ( Ab[i, -1] - np.dot(Ab[i, i + 1:n], x[i + 1:n])) / Ab[i, i]

print("Solution:", x)


Solution: [ 2.25  2.5  -2.  ]


## Understanding `np.dot()` in Back Substitution

During back substitution, some variables have already been calculated. Their contribution to the current equation is calculated using `np.dot()`.

```python
known_term = np.dot(
    Ab[i, i + 1:n],
    x[i + 1:n]
)

# **Question no 04:**

An engineer is designing a structure that involves three unknown forces x1, x2, x3.Based on the force-balance equations, the following system is obtained:

$$2x_1 + x_2 + x_3 = 5$$

$$4x_1 + 4x_2 + 3x_3 = 13$$

$$x_1 + 2x_2 + 2x_3 = 7$$

Use the Gaussian Elimination method to determine the values of the three unknown forces. Verify your solution by substituting the calculated values back into the original system of equations.

In [ ]:
import numpy as np
def guassian_elimination(A,b):    # A = coffiecient Matrix ; b= RHS vector
      A = A.astype(float)
      b = b.astype(float)
      n = len(b)
      Ab= np.column_stack((A,b))
      for i in range(n-1):
        if A[i,i]==0:
          for k in range(i+1,n):
            if A[k,i]!=0:
              Ab[[i,k]]=Ab[[k,i]]
              break
               # Row Replacement
        for j in range(i+1,n):
          factor=Ab[j,i]/Ab[i,i]
          Ab[j]=Ab[j]-factor*Ab[i]
      x=np.zeros(n)
      for i in range(n-1,-1,-1):
        x[i]=(Ab[i,-1]-np.dot(Ab[i,i+1:n],x[i+1:n]))/Ab[i,i]
      return x
A = np.array([
    [2, 1, 1],
    [4, 4, 3],
    [1, 2, 2]
], dtype=float)

b = np.array([5, 13, 7], dtype=float)

solution = guassian_elimination(A, b)

print("Solution:")
for i in range(len(solution)):
    print(f"x{i+1} =", solution[i])


# VERIFICATION

print("\nVerification:")
print("A @ x =", A @ solution)
print("b     =", b)


Solution:
x1 = 1.0
x2 = 0.0
x3 = 3.0

Verification:
A @ x = [ 5. 13.  7.]
b     = [ 5. 13.  7.]


# **Question no 05:**


 A biologist is analyzing a biological sample containing four unknown substances x1, x2, x3, x4. Measurements from different laboratory tests produce the following system of equations:

$$x_1 + 2x_2 + x_3 + 3x_4 = 10$$

$$2x_1 + x_2 + 3x_3 + 2x_4 = 12$$

$$3x_1 + 4x_2 + 2x_3 + x_4 = 15$$

$$x_1 + 3x_2 + 4x_3 + 2x_4 = 16$$

Use the Gaussian Elimination method to determine the concentrations of the four unknown substances. Verify the calculated solution using Ax=b and calculate the residual to evaluate how accurately the solution satisfies the original system.

In [ ]:
import numpy as np
def gaussian_elimination(A,b):    # A = coffiecient Matrix ; b= RHS vector
      A = A.astype(float)
      b = b.astype(float)
      n = len(b)
      Ab= np.column_stack((A,b))
      for i in range(n-1):
        if Ab[i,i]==0:
          for k in range(i+1,n):
            if A[k,i]!=0:
              Ab[[i,k]]=Ab[[k,i]]
              break
               # Row Replacement
        for j in range(i+1,n):
          factor=Ab[j,i]/Ab[i,i]
          Ab[j]=Ab[j]-factor*Ab[i]
      x=np.zeros(n)
      for i in range(n-1,-1,-1):
        x[i]=(Ab[i,-1]-np.dot(Ab[i,i+1:n],x[i+1:n]))/Ab[i,i]
      return x
A = np.array([
    [1, 2, 1, 3],
    [2, 1, 3, 2],
    [3, 4, 2, 1],
    [1, 3, 4, 2]
], dtype=float)

b = np.array([10, 12, 15, 16], dtype=float)
solution = gaussian_elimination(A, b)

print("Solution:")
for i in range(len(solution)):
    print(f"x{i+1} =", solution[i])


# VERIFICATION

print("\nVerification:")
print("A @ x =", A @ solution)
print("b     =", b)

# Residual (How accurately does our calculated solution satisfy the original equation?)
# r = |Ax-b|
residual = np.linalg.norm(A @ solution - b)

print("\nResidual:", residual)


Solution:
x1 = 1.1538461538461533
x2 = 1.6461538461538456
x3 = 1.861538461538461
x4 = 1.230769230769231

Verification:
A @ x = [10. 12. 15. 16.]
b     = [10. 12. 15. 16.]

Residual: 6.153480596427404e-15



**Answer:**

Using Gaussian Elimination, the concentrations of the four biological substances are determined as (x_1, x_2, x_3,) and (x_4). The solution is verified by comparing (Ax) with (b), while the residual confirms the numerical accuracy of the calculated concentrations. A near-zero residual indicates that the obtained solution accurately satisfies the biological measurement equations.


# **Question no 06:**

A biologist is studying the interaction of **three biological populations** in an ecosystem. Based on experimental observations, the relationships between the populations are represented by a system of three linear equations.

Write a Python program using the **Gaussian Elimination method** to determine the population-related unknowns from a user-provided coefficient matrix (A) and RHS vector (b). Verify the calculated solution using (Ax=b) and compute the **residual** to assess the accuracy of the numerical solution.


In [ ]:

import numpy as np
def gaussian_elimination(A,b):    # A = coffiecient Matrix ; b= RHS vector
      A = A.astype(float)
      b = b.astype(float)
      n = len(b)
      Ab= np.column_stack((A,b))
      for i in range(n-1):
        if Ab[i,i]==0:
          for k in range(i+1,n):
            if A[k,i]!=0:
              Ab[[i,k]]=Ab[[k,i]]
              break
               # Row Replacement
        for j in range(i+1,n):
          factor=Ab[j,i]/Ab[i,i]
          Ab[j]=Ab[j]-factor*Ab[i]
      x=np.zeros(n)
      for i in range(n-1,-1,-1):
        x[i]=(Ab[i,-1]-np.dot(Ab[i,i+1:n],x[i+1:n]))/Ab[i,i]
      return x
n = int(input("Enter the number of unknowns: "))


print("\nEnter the coefficient matrix A:")

A = []

for i in range(n):
    row = input(f"Enter row {i + 1}: ")

    row = row.replace("[", "")
    row = row.replace("]", "")
    row = row.replace(",", " ")

    row = list(map(float, row.split()))

    A.append(row)

A = np.array(A)


b = input("Enter b: ")

b = b.replace("[", "")
b = b.replace("]", "")
b = b.replace(",", " ")

b = np.array(list(map(float, b.split())))
solution = gaussian_elimination(A, b)

print("Solution:")
for i in range(len(solution)):
    print(f"x{i+1} =", solution[i])


# VERIFICATION

print("\nVerification:")
print("A @ x =", A @ solution)
print("b     =", b)

# Residual
residual = np.linalg.norm(A @ solution - b)

print("\nResidual:", residual)



Enter the number of unknowns: 4

Enter the coefficient matrix A:
Enter row 1: [1,2,3,4]
Enter row 2: [4,5,6,7]
Enter row 3: [0,9,8,7]
Enter row 4: [5,8,9,7]
Enter b: ]-1,-4,6,7]
Solution:
x1 = -1.5999999999999996
x2 = -2.3999999999999986
x3 = 6.6
x4 = -3.6

Verification:
A @ x = [-1. -4.  6.  7.]
b     = [-1. -4.  6.  7.]

Residual: 1.7404671430534633e-14


**Singular Matrix Test:**

 A singular matrix does not have a unique solution. The algorithm checks for a zero pivot after row pivoting and raises an error when no suitable pivot is available.

# **Question no 07:**

A researcher is analyzing a system of **three interacting biological variables** using a set of linear equations. The researcher wants to develop a reliable computational method that can:

1. Solve a normal system using **Gaussian Elimination with row pivoting**.
2. Verify the calculated solution using (Ax=b).
3. Calculate the **residual** to measure numerical accuracy.
4. Detect a **singular matrix** and report when a unique solution does not exist.
Implement Gaussian Elimination in Python to solve the given normal system and test the algorithm on a singular system. Compare the two cases and explain why detecting a singular matrix is important in real-world modeling.


In [ ]:
import numpy as np

def gaussian_elimination(A, b):
    A = A.astype(float)
    b = b.astype(float)
    n = len(b)
    Ab = np.column_stack((A, b))

    for i in range(n - 1):
        if Ab[i, i] == 0:
            for k in range(i + 1, n):
                if Ab[k, i] != 0:
                    Ab[[i, k]] = Ab[[k, i]]
                    break

            else:
                raise ValueError(
                    "Singular matrix: no unique solution.")

        for j in range(i + 1, n):

            factor = Ab[j, i] / Ab[i, i]

            Ab[j] = Ab[j] - factor * Ab[i]

    if Ab[n - 1, n - 1] == 0:
        raise ValueError( "Singular matrix: no unique solution.")

    x = np.zeros(n)

    for i in range(n - 1, -1, -1):

        x[i] = (Ab[i, -1]- np.dot( Ab[i, i + 1:n], x[i + 1:n] )) / Ab[i, i]
    return x

A = np.array([
    [2, 1, 1],
    [4, 4, 3],
    [1, 2, 2]
], dtype=float)

b = np.array([5, 13, 7], dtype=float)

solution = gaussian_elimination(A, b)

print("\nNormal Matrix Test:")
print("\nSolution:")

for i in range(len(solution)):
    print(f"x{i + 1} =", solution[i])
print("\nVerification:")
print("A @ x =", A @ solution)
print("b     =",b)

residual = np.linalg.norm(A @ solution - b)

print("Residual:", residual)

A_singular = np.array([
    [1, 2, 3],
    [2, 4, 6],
    [1, 1, 1]
], dtype=float)

b_singular = np.array([6, 12, 3], dtype=float)
print("Singular Matrix Test")

try:

    solution_singular = gaussian_elimination(A_singular, b_singular)
    print("Solution:", solution_singular)

except ValueError as error:

    print("Error:", error)


Normal Matrix Test:

Solution:
x1 = 1.0
x2 = 0.0
x3 = 3.0

Verification:
A @ x = [ 5. 13.  7.]
b     = [ 5. 13.  7.]
Residual: 0.0
Singular Matrix Test
Error: Singular matrix: no unique solution.


# **Why detecting a singular matrix is important in real-world modeling:**

Detecting a singular matrix is essential in real-world modeling because it identifies situations where the available equations or data are insufficient to determine a unique solution, helping prevent unreliable predictions and ensuring the mathematical model is computationally robust.

**NumPy Comparison:**

The solution obtained from the implemented Gaussian Elimination method is compared with NumPy's **np.linalg.solve()** function. A very small difference confirms that the implemented algorithm produces an accurate solution.


# **Question no 08:**

Compare the solution obtained using your **Gaussian Elimination method** with NumPy’s `np.linalg.solve()` and calculate the difference between the two solutions. What does a near-zero difference indicate?


In [ ]:

solution = gaussian_elimination(A, b)# Solution obtained from our Gaussian Elimination method
numpy_solution = np.linalg.solve(A, b)
# Display both solutions
print("Our Gaussian Elimination Solution:")
print(solution)
print("\nNumPy Solution:")
print(numpy_solution)
# So, the difference is:
difference = np.linalg.norm(solution - numpy_solution)

print("\nDifference between solutions:", difference)

Our Gaussian Elimination Solution:
[1. 0. 3.]

NumPy Solution:
[ 1. -0.  3.]

Difference between solutions: 0.0


**Conclusion**

Gaussian Elimination was successfully implemented in Python using forward elimination, row pivoting, and back substitution. The computed solution was verified using the residual and compared with NumPy’s built-in linear system solver. The results showed close agreement, confirming the accuracy and reliability of the implemented method.